# This is a basic workflow to help you get started with Actions

name: Deploy Website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # The container image to pull from dockerhub
    container: node:lts-alpine

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Install nuget packages
    - name: Install packages
      run: npm install
    - name: Build website
      run: npm run build
    - name: Make out directory
      run: mkdir out
    - name: Make out dist directory
      run: mkdir out/dist
    - name: Copy index
      uses: canastro/copy-file-action@master
      with:
        source: index.html
        target: out/index.html
    - name: Copy dist
      uses: canastro/copy-file-action@master
      with:
        source: dist/.
        target: out/dist/.
        flags: '-r'
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        # Build directory to deploy
        build_dir: out/dist/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}